### ISSUE TITLE
Try Coral Stick accelerator or similar

### ISSUE THREAD

**Issue by CarlosGual** [curso-verano-iot-uah/frigate#1]
Saturnino told me that he has some Coral stick TPU accelerator and that we should try it out. Let's set this to lowest priority because I don't fully see the use case and I think we would be very limited in terms of code, I think they only accept tflite models.

**Comment by CarlosGual** [comment]
Okey, I checked frigate software and it seems that it can integrate easily a coral TPU accelerator, so I think this should be assigned to Adrián.

**Comment by msalexms** [comment]
Okay, perfect.

**Comment by CarlosGual** [comment]
@adriangarciia could you check if it works?

**Comment by adriangarciia** [comment]
Yes, I have integrated the coral into Friagte and it does work, the inference speed dropped significantly by at least 90%

**Comment by CarlosGual** [comment]
Can you upload it to the repo?
